student/student/urls.py
from django.contrib import admin
from django.urls import path
from enroll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.reg,name="home"),
    path('<int:my_id>/',views.delete,name='delete'),
    path('<int:my_id>/',views.update,name='update')
]

student/enroll/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
    Name=models.CharField(max_length=70)
    Email = models.EmailField(max_length=100)
    Password = models.CharField(max_length=70)

student/enroll/forms.py
from django import forms
from .models import Data

class login(forms.ModelForm):
    class Meta:
        model=Data
        fields=['Name','Email','Password']

        widgets={'Password':forms.PasswordInput(render_value=True)}

student/enroll/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import login
from .models import Data

# Create your views here.
def reg(request):
    if(request.method=='POST'):
        fm=login(request.POST)
        if(fm.is_valid()):
            na=fm.cleaned_data['Name']
            em = fm.cleaned_data['Email']
            pa = fm.cleaned_data['Password']
            gm = Data(Name=na, Email=em,Password=pa)
            gm.save()
            fm=login()


    else:
        fm=login()
    stu=Data.objects.all()
    return render(request,'student/enroll.html',{'form':fm,'st':stu})


def delete(request,my_id):
    if(request.method=='POST'):
        gm=Data.objects.get(pk=my_id)
        gm.delete()
        return HttpResponseRedirect('/')

def update(request,my_id):
    if(request.method=='POST'):
        gm=Data.objects.get(pk=my_id)
        fm=login(request.POST ,instance=gm)
        if(fm.is_valid()):
            fm.save()
    else:
        gm=Data.objects.get(pk=my_id)
        fm=login(instance=gm)
    return render(request,'student/update.html',{'form':fm})

student/enroll/templates/student/enroll.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>enroll</title>
      <link rel="stylesheet" type="text/css" href="{% static 'student/enroll.css' %}">
</head>
<body>
<div class="top"><p id="tx1">Function based View ModelForm CRUD Project</p> </div>
<div class="box1">
    <div class="box2"><p id="tx2">
            Add New Student
    </p> </div>
   <div class="box3">
       <form action="" method="POST">
            {% csrf_token %}
            {% for fields in form %}
                {{fields}}
           {% endfor %}
           <div class="bt1"><input  type="submit" value="Add"></div>
           <p id="a">Name</p>
           <p id="b">Email</p>
           <p id="c">Password</p>
       </form></div>

    <div class="box4"><p id="tx5">Show Student information</p></div>
    <div class="box5">
        {% if form %}
        <table width="900px">
            <tr>
                <th id="a1">Id</th>
                <th id="a2"> Name</th>
                <th id="a3"> Email</th>
                <th id="a4"> Password</th>
                <th id="a5">Action</th>
            </tr>
            {% for f in st %}
            <tr>
                <th>{{f.id}}</th>
                <th>{{f.Name}}</th>
                <th>{{f.Email}}</th>
                <th>{{f.Password}}</th>
                <th>

                    <a href="{% url 'update' f.id %}"> <input type="submit" value="Edit" class="bt2"></a>
                       <form action="{% url 'delete' f.id %}" method="POST">
                        {% csrf_token %}
                    <input type="submit" value="Delete" class="bt3">
                    </form>




                </th>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h3>no data</h3>
        {% endif %}
    </div>


</div>
</body>
</html>

student/enroll/templates/student/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update</title>
    <style>
.top
{
position:absolute;
top:80px;
left:200px;
height:80px;
width:1600px;
background-color:#FA8072;
}
#tx1
{
position:absolute;
left:150px;
font-size:50px;
font-weight:bold;
font-family:Sans-serif;
top:-40px;
}

.box2
{
position:absolute;
top:200px;
left:500px;
height:80px;
width:1000px;
background-color:#87CEEB;
}
#tx2
{
position:absolute;
left:350px;
font-size:20px;
font-weight:bold;
font-family:Sans-serif;
top:5px;
}
.box3
{
position:absolute;
top:290px;
left:500px;
height:500px;
width:1000px;


}
#id_Name
{
position:absolute;
top:80px;
left:40px;
width:80%;
height:30px;
border-radius:10px;
outline:none;
}
#a
{
position:absolute;
top:15px;
left:45px;
font-size:25px;
}

#id_Email
{
position:absolute;
top:180px;
left:40px;
width:80%;
height:30px;
border-radius:10px;
outline:none;
}
#b
{
position:absolute;
top:115px;
left:45px;
font-size:25px;
}
#id_Password
{
position:absolute;
top:280px;
left:40px;
width:80%;
height:30px;
border-radius:10px;
outline:none;
}
#c
{
position:absolute;
top:215px;
left:45px;
font-size:25px;
}

.bt1 input[type='submit']
{
position:absolute;
top:350px;
left:42px;
width:70px;
height:30px;
background-color:green;
border-style:none;
color:f1f1f1;
font-size:16px;
font-weight:bold;
}
.bt1 input[type='submit']:hover
{
color:white;
}
.bt2
{
position:absolute;
top:350px;
left:132px;
width:170px;
height:30px;
background-color:#87CEEB;
border-style:none;
color:f1f1f1;
font-size:16px;
font-weight:bold;
}
#tt1:hover
{
color:white;
}
#tt1
{
position:absolute;
color:black;
left:30px;
top:-10px;
}


    </style>
</head>
<body>
<div class="top"><p id="tx1">Function based View ModelForm CRUD Project</p> </div>
<div class="box1">
    <div class="box2"><p id="tx2">
            Update Student Information
    </p> </div>
    <div class="box3">
       <form action="{% url 'home' %}" method="POST">
            {% csrf_token %}
            {% for fields in form %}
                {{fields}}
           {% endfor %}
           <div class="bt1"><input  type="submit" value="Update"></div>
         <a href="{% url 'home' %}"><div class="bt2"><p id="tt1">Back to home</p></div></a>
           <p id="a">Name</p>
           <p id="b">Email</p>
           <p id="c">Password</p>
       </form></div>
</body>
</html>